spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/watchdog
    username: watchdog
    password: watchdog
  exposed:
    show-sql: true
  data:
    light-db:
      mode: jedis
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
logging:
  level:
    i.server: debug
