spring:
  h2:
    console:
      enabled: false
  exposed:
    generate-ddl: true
    excluded-packages: i.server.utils,i.server.handler
  profiles:
    default: prod
  application:
    name: "WatchDogServer"
server:
  port: 8090
